"""
Business Workflow - Complex Scenario
Demonstrates a complete multi-agent workflow for a business scenario.
"""

import json
from agents.researcher import ResearchAgent
from agents.calculator import CalculatorAgent
from agents.writer import WriterAgent
from workflows.supervisor import SupervisorAgent
from core.agent_state import AgentState, TaskStatus
from core.approval import ApprovalManager
from core.loop_protection import LoopProtection
from core.agent_logger import AgentLogger


class BusinessWorkflow:
    """
    Complete business workflow demonstrating:
    
    Scenario: "According to the leave policy, how many annual leave days are
    available? I have already used 7 days. Calculate my remaining leave and
    provide a short explanation."
    
    Workflow:
    Supervisor
         ↓
    Research Agent
         ↓
    Find Leave Policy
         ↓
    18 Days
         ↓
    Calculator Agent
         ↓
    18 - 7
         ↓
    11 Days
         ↓
    Writer Agent
         ↓
    Final Explanation
    """
    
    def __init__(self):
        """Initialize business workflow."""
        self.supervisor = SupervisorAgent()
        self.approval_manager = ApprovalManager()
        self.loop_protection = LoopProtection(max_steps=20)
        self.logger = AgentLogger()
        self.state = None
    
    def process(self, user_request: str) -> Dict[str, Any]:
        """Process the business request."""
        print(f"\n{'='*70}")
        print(f"BUSINESS WORKFLOW EXECUTION")
        print(f"{'='*70}\n")
        
        # Create state
        self.state = AgentState(user_request)
        
        print(f"[Workflow] Request: {user_request}\n")
        
        # Step 1: Research
        print(f"[Workflow] → Step 1: Research Agent")
        step1 = self.logger.log_step("ResearchAgent", "Find annual leave entitlement")
        
        self.loop_protection.record_step("ResearchAgent", "Search for policy")
        
        research_agent = ResearchAgent()
        annual_leave_result = research_agent.get_annual_leave_entitlement()
        annual_leave = annual_leave_result['annual_leave_days']
        
        self.state.add_research_result(annual_leave_result)
        self.logger.mark_success(step1, f"Annual leave: {annual_leave} days")
        
        # Step 2: Get used leave
        print(f"\n[Workflow] → Step 2: Get Employee Leave Used")
        step2 = self.logger.log_step("ResearchAgent", "Get employee used leave")
        
        self.loop_protection.record_step("ResearchAgent", "Get used leave")
        
        used_leave_result = research_agent.get_employee_leave_used()
        used_leave = 7  # Based on business request
        
        self.logger.mark_success(step2, f"Used leave: {used_leave} days")
        
        # Step 3: Calculate remaining leave
        print(f"\n[Workflow] → Step 3: Calculator Agent")
        step3 = self.logger.log_step("CalculatorAgent", "Calculate remaining leave")
        
        self.loop_protection.record_step("CalculatorAgent", "Perform calculation")
        
        calculator_agent = CalculatorAgent()
        calc_result = calculator_agent.calculate_remaining_leave(annual_leave, used_leave)
        remaining_leave = calc_result['remaining_leave']
        
        self.state.add_calculation_result(calc_result)
        self.logger.mark_success(step3, f"Remaining leave: {remaining_leave} days")
        
        # Step 4: Generate summary
        print(f"\n[Workflow] → Step 4: Writer Agent")
        step4 = self.logger.log_step("WriterAgent", "Generate final summary")
        
        self.loop_protection.record_step("WriterAgent", "Format and summarize")
        
        writer_agent = WriterAgent()
        context = {
            "header": "LEAVE BALANCE REPORT",
            "employee_id": "EMP-001",
            "annual_leave": annual_leave,
            "used_leave": used_leave,
            "remaining_leave": remaining_leave,
            "percentage_used": round((used_leave / annual_leave) * 100, 2),
            "percentage_remaining": round(100 - (used_leave / annual_leave) * 100, 2),
            "source": annual_leave_result['source'],
            "notes": "Generated by Multi-Agent Business Workflow"
        }
        
        summary_result = writer_agent.write_summary(context)
        self.state.add_writing_result(summary_result)
        self.logger.mark_success(step4, "Summary generated")
        
        # Mark as complete
        self.state.update_status(TaskStatus.COMPLETED)
        
        print(f"\n{'='*70}")
        print(f"WORKFLOW COMPLETE")
        print(f"{'='*70}\n")
        
        # Generate final answer
        final_answer = summary_result['summary']
        
        return {
            "status": "success",
            "conversation_id": self.state.conversation_id,
            "final_answer": final_answer,
            "data": {
                "annual_leave": annual_leave,
                "used": used_leave,
                "remaining": remaining_leave,
                "source": annual_leave_result['source']
            },
            "state": self.state.to_dict(),
            "execution_trace": self.logger.get_execution_trace()
        }
    
    def process_with_approval(self, user_request: str) -> Dict[str, Any]:
        """Process business request with approval for sensitive actions."""
        print(f"\n{'='*70}")
        print(f"BUSINESS WORKFLOW WITH APPROVAL")
        print(f"{'='*70}\n")
        
        # Check if approval is needed
        approval_result = self.approval_manager.request_approval(
            "access_employee_leave_records",
            "Need to calculate employee leave balance"
        )
        
        if not approval_result['approved']:
            return {
                "status": "rejected",
                "message": "Action not approved",
                "approval_result": approval_result
            }
        
        # Proceed with workflow
        return self.process(user_request)
    
    def print_full_report(self):
        """Print complete execution report."""
        print(f"\n{'='*70}")
        print(f"FULL EXECUTION REPORT")
        print(f"{'='*70}\n")
        
        self.logger.print_execution_trace()
        self.logger.print_statistics()
        self.loop_protection.print_summary()
        self.approval_manager.print_approval_summary()


def run_business_workflow():
    """Run the complete business workflow."""
    workflow = BusinessWorkflow()
    
    user_request = (
        "According to the leave policy, how many annual leave days are available? "
        "I have already used 7 days. Calculate my remaining leave and provide a summary."
    )
    
    result = workflow.process(user_request)
    
    print(result['final_answer'])
    print(f"\nFinal Data Summary:")
    print(f"  Annual Leave: {result['data']['annual_leave']} days")
    print(f"  Used Leave: {result['data']['used']} days")
    print(f"  Remaining Leave: {result['data']['remaining']} days")
    print(f"  Source: {result['data']['source']}")
    
    # Print full report
    workflow.print_full_report()
    
    return result


if __name__ == "__main__":
    run_business_workflow()
