"""
Writer Agent
Responsible for summarization, formatting, and final response generation.
"""

import json
from typing import Dict, Any, List


class WriterAgent:
    """
    Writer Agent handles summarization, formatting, and final response generation.
    
    Responsibilities:
    - Summarization
    - Formatting output
    - Final response generation
    - Report creation
    """
    
    def __init__(self, name: str = "WriterAgent"):
        self.name = name
    
    def write_summary(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Write a summary based on context data.
        
        Args:
            context: Context dictionary with data to summarize
            
        Returns:
            Dict with formatted summary
        """
        print(f"\n[Writer Agent] Creating summary from context")
        
        summary_text = self._build_summary(context)
        
        return {
            "status": "success",
            "summary": summary_text,
            "formatted": True,
            "context_keys": list(context.keys())
        }
    
    def _build_summary(self, context: Dict[str, Any]) -> str:
        """Build a formatted summary from context."""
        lines = []
        
        if "header" in context:
            lines.append(f"\n{'='*60}")
            lines.append(f"{context['header']}")
            lines.append(f"{'='*60}\n")
        
        if "employee_id" in context:
            lines.append(f"Employee ID: {context['employee_id']}")
        
        if "annual_leave" in context:
            lines.append(f"Annual Leave Entitlement: {context['annual_leave']} days")
        
        if "used_leave" in context:
            lines.append(f"Leave Used in 2026: {context['used_leave']} days")
        
        if "remaining_leave" in context:
            remaining = context['remaining_leave']
            lines.append(f"Leave Remaining: {remaining} days")
            
            if remaining > 0:
                lines.append(f"\n✓ Status: You have sufficient leave remaining.")
            else:
                lines.append(f"\n✗ Status: No leave remaining (over-utilized).")
        
        if "percentage_used" in context:
            lines.append(f"Percentage Used: {context['percentage_used']}%")
            lines.append(f"Percentage Remaining: {context['percentage_remaining']}%")
        
        if "source" in context:
            lines.append(f"\nSource: {context['source']}")
        
        if "notes" in context:
            lines.append(f"\nNotes: {context['notes']}")
        
        lines.append(f"\n{'='*60}\n")
        
        return '\n'.join(lines)
    
    def format_json_response(self, data: Dict[str, Any]) -> str:
        """Format data as JSON."""
        return json.dumps(data, indent=2)
    
    def format_markdown(self, title: str, sections: Dict[str, str]) -> str:
        """Format content as Markdown."""
        lines = [f"# {title}\n"]
        
        for section_title, content in sections.items():
            lines.append(f"## {section_title}")
            lines.append(content)
            lines.append("")
        
        return '\n'.join(lines)
    
    def create_leave_summary(self, annual_leave: int, used_leave: int, 
                            employee_id: str = "EMP-001") -> Dict[str, Any]:
        """
        Create a leave summary report.
        
        Args:
            annual_leave: Total annual leave
            used_leave: Leave used
            employee_id: Employee identifier
            
        Returns:
            Dict with formatted summary
        """
        remaining = annual_leave - used_leave
        percentage_used = (used_leave / annual_leave) * 100
        percentage_remaining = 100 - percentage_used
        
        context = {
            "header": "LEAVE BALANCE REPORT",
            "employee_id": employee_id,
            "annual_leave": annual_leave,
            "used_leave": used_leave,
            "remaining_leave": remaining,
            "percentage_used": round(percentage_used, 2),
            "percentage_remaining": round(percentage_remaining, 2),
            "source": "leave_policy.pdf",
            "notes": "This report was generated by the Multi-Agent System"
        }
        
        summary = self.write_summary(context)
        
        return {
            "status": "success",
            "report": summary['summary'],
            "data": context
        }
    
    def format_employee_response(self, employee_name: str, 
                                annual_leave: int, used_leave: int) -> str:
        """Format a professional response for an employee."""
        remaining = annual_leave - used_leave
        
        response = f"""
Dear {employee_name},

Based on the company leave policy and your current leave records:

• Annual Leave Entitlement: {annual_leave} working days
• Leave Used in 2026: {used_leave} days
• Leave Remaining: {remaining} days

You have {remaining} working days of annual leave remaining for the current year.
Please note that unused leave can carry over a maximum of 5 days to the next year.

For any leave requests, please submit them at least 2 weeks in advance.

Best regards,
HR Department
        """
        
        return response.strip()
    
    def summarize_agent_workflow(self, workflow_steps: List[Dict[str, Any]]) -> str:
        """Summarize the agent workflow steps."""
        lines = ["\n" + "="*60]
        lines.append("AGENT WORKFLOW SUMMARY")
        lines.append("="*60 + "\n")
        
        for i, step in enumerate(workflow_steps, 1):
            lines.append(f"Step {i}: {step.get('agent', 'Unknown')}")
            lines.append(f"  Action: {step.get('action', 'Unknown')}")
            lines.append(f"  Result: {step.get('result', 'Unknown')}")
            lines.append(f"  Status: {step.get('status', 'Unknown')}\n")
        
        lines.append("="*60 + "\n")
        
        return '\n'.join(lines)


if __name__ == "__main__":
    agent = WriterAgent()
    
    # Test leave summary
    report = agent.create_leave_summary(18, 7, "EMP-001")
    print(report['report'])
    
    # Test formatted response
    response = agent.format_employee_response("John Smith", 18, 7)
    print(response)
